import { config } from 'dotenv'
import argv from 'minimist'

export const isProduction = Boolean(argv(process.argv.slice(2)).production)

config({ path: isProduction ? '.env.prod' : '.env.dev' })

export const envConfig = {
  PORT: process.env.PORT,

  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_NAME: process.env.DB_NAME,

  DB_USERS_COLLECTION: process.env.DB_USERS_COLLECTION,
  DB_REFRESH_TOKENS_COLLECTION: process.env.DB_REFRESH_TOKENS_COLLECTION,
  DB_FOLLOWS_COLLECTION: process.env.DB_FOLLOWS_COLLECTION,
  DB_TWEETS_COLLECTION: process.env.DB_TWEETS_COLLECTION,
  DB_HASHTAGS_COLLECTION: process.env.DB_HASHTAGS_COLLECTION,
  DB_BOOKMARKS_COLLECTION: process.env.DB_BOOKMARKS_COLLECTION,
  DB_LIKES_COLLECTION: process.env.DB_LIKES_COLLECTION,
  DB_CONVERSATIONS_COLLECTION: process.env.DB_CONVERSATIONS_COLLECTION,

  PASSWORD_SECRET: process.env.PASSWORD_SECRET,

  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
  JWT_VERIFY_EMAIL_TOKEN_SECRET: process.env.JWT_VERIFY_EMAIL_TOKEN_SECRET,
  JWT_FORGOT_PASSWORD_TOKEN_SECRET: process.env.JWT_FORGOT_PASSWORD_TOKEN_SECRET,

  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,
  VERIFY_EMAIL_TOKEN_LIFE: process.env.VERIFY_EMAIL_TOKEN_LIFE,
  FORGOT_PASSWORD_TOKEN_LIFE: process.env.FORGOT_PASSWORD_TOKEN_LIFE,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,

  CLIENT_REDIRECT_CALLBACK_URI: process.env.CLIENT_REDIRECT_CALLBACK_URI,
  CLIENT_URI: process.env.CLIENT_URI,

  AWS_REGION: process.env.AWS_REGION,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  AWS_REGISTER_EMAIL: process.env.AWS_REGISTER_EMAIL,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME
} as Record<string, string>
